security:
    password_hashers:
        App\Entity\Patient:
            algorithm: auto
        App\Entity\Doctor:
            algorithm: auto
        App\Entity\AdminStaff:
            algorithm: auto

    providers:
        multi_user_provider:
            id: App\Security\UserProvider

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: App\Security\LoginFailureHandler

        api:
            pattern: ^/api
            stateless: true
            provider: multi_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/registration, roles: PUBLIC_ACCESS }